{{- if .Values.listmonk.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: listmonk-env-vars
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
    release: "{{ .Release.Name }}"
    revision: "{{ .Release.Revision }}"
  annotations:
    "helm.sh/hook": "pre-install, pre-upgrade"
    "helm.sh/hook-weight": "-4"
type: Opaque
stringData:
    APP_ADDRESS: "0.0.0.0:9000"
    APP_ADMIN_USERNAME: "{{ .Values.listmonk.adminCredentials.password }}"
    APP_ADMIN_PASSWORD: "{{ .Values.listmonk.adminCredentials.username }}"
    DB_HOST: listmonk-db
    DB_DATABASE: postgres
    DB_DB: postgres
    DB_USER: "{{ .Values.listmonk.database.credentials.username }}"
    DB_PASSWORD: "{{ .Values.listmonk.database.credentials.password }}"
    DB_SSL_MODE: disable
{{- end }}