apiVersion: v1
kind: Secret
metadata:
  name: listmonk-settings
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
    release: "{{ .Release.Name }}"
    revision: "{{ .Release.Revision }}"
  annotations:
    "helm.sh/hook": "pre-install, pre-upgrade"
    "helm.sh/hook-weight": "-4"
type: Opaque
stringData:
  config.json: |-
    {
      "username": "{{  .Values.listmonk.adminCredentials.username }}",
      "password": "{{  .Values.listmonk.adminCredentials.password }}",
      "rootUrl": "{{ .Values.listmonk.ingress.host }}",
      "settingsEndpoint": "http://listmonk-app/api/settings",
      "general": {
          "defaultFromEmail": "{{ .Values.listmonk.settings.general.defaultFromEmail }}",
          "enablePublicSubscriptionPage": "{{ .Values.listmonk.settings.general.enablePublicSubscriptionPage }}",
          "adminNotificationEmails": {{ .Values.listmonk.settings.general.adminNotificationEmails | toJson }}
      },
      "mediaUploads": {
        "provider": "{{ .Values.listmonk.settings.mediaUploads.provider }}",
        "uploadPath": "{{ .Values.listmonk.settings.mediaUploads.uploadPath }}"
      },
      "smtp": {
          "host": "{{ .Values.listmonk.settings.smtp.host }}",
          "port": "{{ .Values.listmonk.settings.smtp.port }}",
          "username": "{{ .Values.listmonk.settings.smtp.username }}",
          "password": "{{ .Values.listmonk.settings.smtp.password }}",
          "authProtocol": "{{ .Values.listmonk.settings.smtp.authProtocol }}",
          "tlsEnabled": "{{ .Values.listmonk.settings.smtp.authProtocol }}",
          "skipTlsVerification": "{{ .Values.listmonk.settings.smtp.skipTlsVerification }}"   
      }
    }