listmonk:
  enabled: true
  image:
    repository: listmonk/listmonk
    pullPolicy: IfNotPresent
    tag: "v2.0.0"
  ingress:
    enabled: true
    host: newsletter.gymtrack.nl
  adminCredentials:
    username: admin
    password: admin
  # persistent volume used for media uploads
  persistentVolume:
    capacity: 50Mi
    storageClass: longhorn
  database:
    # if create is true a new dedicated postgres container will be deployed
    create: true
    # if init is true a job will be scheduled to initialize the database 
    init: true
    image:
      repository: postgres
      pullPolicy: IfNotPresent
      tag: "12.5-alpine"
    credentials:
      username: listmonkdbusername
      password: listmonkdbpassword
    persistentVolume:
      capacity: 256Mi
      storageClass: longhorn
  settings:
    # if import is true a job will be scheduled to import smtp settings through api call on installs and upgrades
    # use with care since this will override settings that has been made through the ui.
    import: true
    image:
      repository: bamaas/listmonk_import
      pullPolicy: IfNotPresent
      tag: "2"
    general:
      logo: resources/listmonk-logo.jpg
      # Default `from` e-mail to show on outgoing campaign e-mails. 
      defaultFromEmail: "bas <noreply@listmonk.yoursite.com>"
      # list of e-mail addresses to which admin notifications such as import updates, campaign completion, failure etc. should be sent.
      adminNotificationEmails: 
        - admin@listmonk.yoursite.com
    smtp:
      host: "smtpServerHost"
      port: "465"
      username: "ditiseentest"
      password: "smtpServerPassword"
      authProtocol: "plain"
      tlsEnabled: "true"
      skipTlsVerification: "false"